services:
  central:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MAIN_CLASS: com.votingsystem.rmi.central.CentralServerMain
    container_name: central-server
    ports:
      - "1099:1099" # Porta padrão RMI
    networks:
      - votenet

  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MAIN_CLASS: com.votingsystem.rmi.server.VotingServerMain
    container_name: voting-server
    depends_on:
      - central
    networks:
      - votenet

  client:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MAIN_CLASS: com.votingsystem.rmi.client.VotingClient
    container_name: voting-client
    depends_on:
      - central
      - server
    networks:
      - votenet
    stdin_open: true
    tty: true

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: voting-system
      MONGO_INITDB_ROOT_USERNAME: bancodeDatabase
      MONGO_INITDB_ROOT_PASSWORD: askjKLSDJFBN342523ASKJDFNasasfkjnadsfkjadfb34634
    volumes:
      - mongodb_data:/data/db
    networks:
      - votenet

networks:
  votenet:
    driver: bridge

volumes:
  mongodb_data: